---
title: "Fit final models"
author: "Aaron Till and Andrew Bray"
date: "1/28/2019"
output: html_document
---

## Load packages

```{r}
library(tidyverse)
library(rsample)
library(caret)
library(glmnet)
library(Matrix)
library(e1071)
library(pROC)
library(PRROC) 
library(glmnetUtils)
library(doParallel)
library(lme4)
```

## Load 

```{r}
setwd("data/processed/")
historical_data <- read_csv("historical_data.csv",
                            col_types = list(wbic = col_character(),
                                             year = col_character(),
                                             month  = col_character(),
                                             season = col_character(),
                                             summerkill = col_character(),
                                             ice_duration = col_double())) %>%
  select(-cause.category.4, -anthropogenic, -infectious, -unknown, -winterkill) %>%
  mutate(summerkill = fct_recode(as.factor(summerkill),
                                 "neg" = "0",
                                 "pos" = "1"))
```

Scale data.

```{r}
pre_proc_values <- preProcess(historical_data, method = c("center", "scale"))
historical_data  <- predict(pre_proc_values, historical_data)
```


## Fit final models

Specify predictor set and control parameters.

```{r}
f1 <- summerkill ~ variance_after_ice_30 + variance_after_ice_60 + log_schmidt +
  cumulative_above_10 + ice_duration + population + lon + lat + season + temp

control_logloss_ds <- trainControl(method = "repeatedcv",
                                   number = 5,
                                   repeats = 5,
                                   summaryFunction = mnLogLoss,
                                   classProbs = TRUE,
                                   sampling = "down")
```

### Logisitic f1

```{r}
final_logistic_f1 <- glm(f1,
                         historical_data,
                         family = "binomial") 
#final_logistic_f1_backwards <- step(final_logistic_f1_backwards)
write_rds(final_logistic_f1, "../models/final_logistic_f1.rds")
```

### Lasso f1, logloss, with downsampling

```{r}
cl <- makePSOCKcluster(4)
registerDoParallel(cl)

par_grid <-  expand.grid(alpha = 1,
                         lambda = 10^seq(-3, -1, length = 10))

set.seed(825)
final_lasso_f1_logloss_downsampled <- train(f1, 
                                            data = historical_data, 
                                            method = "glmnet", 
                                            metric = "logLoss",
                                            tuneGrid = par_grid,
                                            trControl = control_logloss_ds)
stopCluster(cl)
write_rds(final_lasso_f1_logloss_downsampled, "../models/final_lasso_f1_logloss.rds")
```


### Ridge f1, logloss, with downsampling

```{r}
par_grid <-  expand.grid(alpha = 0,
                         lambda = 10^seq(-1.7, -1.3, length = 10))
cl <- makePSOCKcluster(4)
registerDoParallel(cl)
set.seed(825)
final_ridge_f1_logloss_downsampled <- train(f1, 
                                            data = historical_data, 
                                            method = "glmnet",
                                            metric = "logLoss",
                                            tuneGrid = par_grid,
                                            trControl = control_logloss_ds)
stopCluster(cl)
write_rds(final_ridge_f1_logloss_downsampled, "../models/final_ridge_f1_logloss_downsampled.rds")
```

### Predictive model

```{r}
cl <- makePSOCKcluster(4)
registerDoParallel(cl)

par_grid <-  expand.grid(alpha = 1,
                         lambda = seq(.01, .04, length.out = 6))

set.seed(825)
predictive_logistic <- train(summerkill ~ variance_after_ice_30 + 
                            variance_after_ice_60 + log_schmidt +
                            cumulative_above_10 + population + 
                            lon + lat + season + temp, 
                          data = historical_data, 
                          method = "glmnet", 
                          metric = "logLoss",
                          tuneGrid = par_grid,
                          trControl = control_logloss_ds)
stopCluster(cl)

```




# A: remove season, correct ps
```{r}
cl <- makePSOCKcluster(4)
registerDoParallel(cl)

par_grid <-  expand.grid(alpha = 1,
                         lambda = seq(.01, .04, length.out = 6))

set.seed(825)
m <- train(summerkill ~ variance_after_ice_30 + 
                            variance_after_ice_60 + log_schmidt +
                            cumulative_above_10 + population + 
                            lon + lat + temp, 
                          data = historical_data, 
                          method = "glmnet", 
                          metric = "logLoss",
                          tuneGrid = par_grid,
                          trControl = control_logloss_ds)
stopCluster(cl)
write_rds(m, "../models/predictive_lasso_A.rds")
```

# B: remove season, correct b0
```{r}
prev <- mean(historical_data$summerkill == "pos")
n_1 <- 77 #sum(historical_data$summerkill == "pos")
n_0 <- 77 #sum(historical_data$summerkill == "neg")
ind_opt <- which.min(abs(m$finalModel$lambda -
                           m$finalModel$lambdaOpt))
m$finalModel$a0[ind_opt] <- m$finalModel$a0[ind_opt] - 
  log(((1 - prev)/prev)*(n_1/n_0))
write_rds(m, "../models/predictive_lasso_B.rds")
```

# C: Correct ps
```{r}
cl <- makePSOCKcluster(4)
registerDoParallel(cl)

par_grid <-  expand.grid(alpha = 1,
                         lambda = seq(.01, .04, length.out = 6))

set.seed(825)
m <- train(summerkill ~ variance_after_ice_30 + 
                            variance_after_ice_60 + log_schmidt +
                            cumulative_above_10 + population + 
                            lon + lat + season + temp, 
                          data = historical_data, 
                          method = "glmnet", 
                          metric = "logLoss",
                          tuneGrid = par_grid,
                          trControl = control_logloss_ds)
stopCluster(cl)
write_rds(m, "../models/predictive_lasso_C.rds")
```

# D: Correct B0
```{r}
prev <- mean(historical_data$summerkill == "pos")
n_1 <- 77 #sum(historical_data$summerkill == "pos")
n_0 <- 77 #sum(historical_data$summerkill == "neg")
ind_opt <- which.min(abs(m$finalModel$lambda -
                           m$finalModel$lambdaOpt))
m$finalModel$a0[ind_opt] <- m$finalModel$a0[ind_opt] - 
  log(((1 - prev)/prev)*(n_1/n_0))
write_rds(m, "../models/predictive_lasso_D.rds")
```

# E: Final ridge f1 logloss
```{r}
control_logloss <- trainControl(method = "repeatedcv",
                                   number = 5,
                                   repeats = 3,
                                   summaryFunction = mnLogLoss,
                                   classProbs = TRUE)
cl <- makePSOCKcluster(4)
registerDoParallel(cl)

par_grid <-  expand.grid(alpha = 0,
                         lambda = 10^seq(-3, -1, length = 8))

set.seed(825)
predictive_lasso <- train(summerkill ~ variance_after_ice_30 + 
                            variance_after_ice_60 + log_schmidt +
                            cumulative_above_10 + population + 
                            lon + lat + season + temp, 
                          data = historical_data, 
                          method = "glmnet", 
                          metric = "logLoss",
                          tuneGrid = par_grid,
                          trControl = control_logloss)
stopCluster(cl)
write_rds(predictive_lasso, "../models/predictive_lasso_E.rds")
```

# F Lasso fit with cv.glmnet

```{r}
library(doMC)
registerDoMC(cores = 4)

X <- model.matrix(summerkill ~ variance_after_ice_30 + 
                    variance_after_ice_60 + log_schmidt +
                    cumulative_above_10 + population + 
                    lon + lat + season + temp, 
                  data = historical_data)
model <- cv.glmnet(X, historical_data$summerkill,
                   lambda = 10^seq(-5, -1, length.out = 20),
  family = "binomial",
    type.measure = "auc",
  parallel = TRUE, 
  keep = TRUE,
  alpha = 0
)

X <- model.matrix(summerkill ~ variance_after_ice_30 + 
                    variance_after_ice_60 + log_schmidt +
                    cumulative_above_10 + population + 
                    lon + lat + temp, 
                  data = historical_data)
model2 <- cv.glmnet(X, historical_data$summerkill,
                   lambda = 10^seq(-8, -1, length.out = 12),
  family = "binomial",
  parallel = TRUE, 
  keep = TRUE
)
write_rds(model, "../models/predictive_lasso_F.rds")
```

