---
title: "Assess Models"
author: "Aaron Till and Andrew Bray"
output: html_document
---

```{r}
library(tidyverse)
library(caret)
library(glmnet)
library(Matrix)
library(e1071)
library(broom)
```


## Load diagnostic functions

```{r}
plot_coefs <- function(tidy_model) {
  tidy_model %>%
    ggplot(aes(fct_reorder(term, estimate), estimate, fill = estimate > 0)) +
    geom_col(alpha = 0.8, show.legend = FALSE) +
    coord_flip() +
    labs(x = NULL)
}

plot_timeseries <- function(model, future_data, historical_data) {
  predictions <- predict(object = model, 
                         newdata = future, 
                         type = "response")
  
  f_data <- future %>%
    add_column(prob = predictions) %>%
    group_by(year) %>%
    summarize(temp       = mean(mean_surf),
              kills      = sum(prob)) 
  
  f_early <- f_data %>%
    filter(year < 2075) %>%
    mutate(kills_smooth = loess(kills ~ year, .)$fitted)
  
  f_late <- f_data %>%
    filter(year > 2075) %>%
    mutate(kills_smooth = loess(kills ~ year, .)$fitted)
  
  hist_data <- historical_data %>% 
    filter(year < 2014) %>%
    group_by(year) %>%
    summarize(temp = mean(mean_surf),
              kills = sum(summerkill == 1)) %>%
    mutate(kills_smooth = loess(kills ~ year, .)$fitted)
  
  gap_data <- tibble(year = c(2014:2040, 2060:2080))
  
  full_data <- f_early %>%
    bind_rows(f_late, hist_data, gap_data)
  
  # Construct timeseries plot
  ggplot(full_data, aes(x = year)) +
    geom_rect(xmin = 2015, xmax = 2040, ymin = 0, ymax = 110, fill = "lightgray", alpha = .002) +
    geom_rect(xmin = 2060, xmax = 2080, ymin = 0, ymax = 110, fill = "gray", alpha = .002) +
    geom_line(aes(y = kills_smooth)) +
    ylab("Total Predicted Summerkills") +
    xlab(NULL) +
    theme_bw()
}
```

## Load and partition data

```{r}
setwd("data/prepared_for_modeling/")
training <- read_csv("training.csv",
                     col_types = list(wbic = col_character(),
                                      year = col_character(),
                                      month  = col_character(),
                                      season = col_character(),
                                      summerkill = col_character(),
                                      ice_duration = col_double())) %>%
  mutate(summerkill = as.factor(summerkill))

testing <- read_csv("testing.csv",
                    col_types = list(wbic = col_character(),
                                     year = col_character(),
                                     month  = col_character(),
                                     season = col_character(),
                                     ice_duration = col_double())) %>%
  mutate(summerkill = as.factor(summerkill))
```

## Load models

```{r}
setwd("../models") 
model_names <- list.files()
all_models <- model_names %>%
  map(., ~read_rds(.x))
all_models <- tibble(name  = model_names,
                     model = all_models)
```

## Coefficient plots

```{r}
# LASSO
m <- lasso_f1_logloss$finalModel %>%
  coef(lasso_f1_logloss$bestTune$lambda) 
coef_lasso_f1_logloss <- tibble(term = row.names(m), estimate = m[,1]) %>%
  filter(term != "(Intercept)") %>%
  select(term, estimate) %>%
  add_column(model = "Lasso F1, logloss")
plot_coefs(coef_lasso_f1_logloss)

m <- lasso_f1_logloss_downsampled$finalModel %>%
  coef(lasso_f1_logloss_downsampled$bestTune$lambda) 
coef_lasso_f1_logloss_downsampled <- tibble(term = row.names(m), estimate = m[,1]) %>%
  filter(term != "(Intercept)") %>%
  select(term, estimate) %>%
  add_column(model = "Lasso F1, logloss, downsampled")
plot_coefs(coef_lasso_f1_logloss_downsampled)

m <- lasso_f2_logloss$finalModel %>%
  coef(lasso_f2_logloss$bestTune$lambda) 
coef_lasso_f2_logloss <- tibble(term = row.names(m), estimate = m[,1]) %>%
  filter(term != "(Intercept)") %>%
  select(term, estimate) %>%
  add_column(model = "Lasso F2, logloss")
plot_coefs(coef_lasso_f2_logloss)

m <- lasso_f2_logloss_downsampled$finalModel %>%
  coef(lasso_f2_logloss_downsampled$bestTune$lambda) 
coef_lasso_f2_logloss_downsampled <- tibble(term = row.names(m), estimate = m[,1]) %>%
  filter(term != "(Intercept)") %>%
  select(term, estimate) %>%
  add_column(model = "Lasso F2, logloss, downsampled")
plot_coefs(coef_lasso_f2_logloss_downsampled)

# Ridge
  
# Random Effects
coef_re_f1 <- re_f1 %>%
  tidy() %>%
  filter(group == "fixed") %>%
  filter(term != "(Intercept)") %>%
  filter(p.value <= .3) %>%
  select(term, estimate) %>%
  add_column(model = "Random Effects")
plot_coefs(coef_re_f1)

# Combined
bind_rows(coef_lasso_f1_logloss,
          coef_lasso_f1_logloss_downsampled,
          coef_lasso_f2_logloss,
          coef_lasso_f2_logloss_downsampled,
          coef_re_f1) %>%
  ggplot(aes(x = fct_reorder(term, estimate), 
             y = estimate, 
             fill = estimate > 0)) +
  geom_col(show.legend = FALSE) +
  facet_grid(~ model) +
  coord_flip() +
  labs(x = NULL) +
  theme_bw()
```

## Metrics

Extract fitted values.

```{r}
predict_route(model, newdata) {
  if("train" %in% class(model)) {
    predict(model, newdata, "prob")
  } else {predict(model, newdata, "response")}
}

p <- all_models %>%
```

Calculate metrics.

```{r}
testing %>%
  select(summerkill) %>%
  bind_cols(p_lasso_f1_logloss) %>%
  mutate(predicted = as.factor(ifelse(pos > .5, "pos", "neg"))) %>%
  metrics(truth = summerkill, estimate = predicted)
  roc_auc(summerkill, pos)

testing %>%
  select(summerkill) %>%
  bind_cols(p_lasso_f1_logloss_downsampled) %>%
  roc_auc(summerkill, pos)
```

## Future preditions



