---
title: "Fit Models"
author: "Aaron Till and Andrew Bray"
output: html_document
---

```{r}
library(tidyverse)
library(rsample)
library(caret)
library(glmnet)
library(Matrix)
library(e1071)
library(pROC)
library(PRROC) 
library(glmnetUtils)
```

## Prepare data

```{r}
setwd("data/processed/")
historical_data <- read_csv("historical_data.csv",
                            col_types = list(wbic = col_factor(NULL),
                                             month  = col_factor(NULL),
                                             season = col_factor(NULL),
                                             summerkill = col_factor(NULL),
                                             ice_duration = col_double())) %>%
  select(-cause.category.4)

future_data <- read_csv("future_data.csv",
                            col_types = list(wbic = col_factor(NULL),
                                             month  = col_factor(NULL),
                                             season = col_factor(NULL),
                                             ice_duration = col_double()))
```

```{r}
set.seed(998)
in_training <- createDataPartition(historical_data$summerkill,
                                  p = .75, list = FALSE)

training <- historical_data %>%
  mutate(summerkill = fct_recode(summerkill,
                                 "neg" = "0",
                                 "pos" = "1")) %>%
  slice(in_training)
testing  <- historical_data %>%
  mutate(summerkill = fct_recode(summerkill,
                                 "neg" = "0",
                                 "pos" = "1")) %>%
  slice(-in_training)
```

In order to compare coefficients, we center and scale the predictors.

```{r}
pre_proc_values <- preProcess(training, method = c("center", "scale"))
training <- predict(pre_proc_values, training)
testing  <- predict(pre_proc_values, testing)
```


## Model 1: Lasso Logistic

```{r}
f1 <- summerkill ~ variance_after_ice_30 + variance_after_ice_60 + log_schmidt +
  cumulative_above_10 + ice_duration + population + lon + lat + season + temp
```

We first fit LASSO models with many difference lambdas, utilizing a 5-fold CV
scheme, repeated once, on the training data.

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 2,
                           summaryFunction = mnLogLoss,
                           classProbs = TRUE)

library(doParallel)
cl <- makePSOCKcluster(6)
registerDoParallel(cl)

par_grid <-  expand.grid(alpha = 1,
                        lambda = seq(1.8e-6, 3.5e-6, 
                                     length.out = 4))


set.seed(825)
lasso_fit_1 <- train(f, 
                     data = training, 
                     method = "glmnet", 
                     metric = "mnLogLoss",
                     tuneGrid = par_grid,
                     trControl = fitControl)
stopCluster(cl)
write_rds(lasso_fit_1, "../models/lasso_fit_1.rds")

ggplot(lasso_fit_1)
ggplot(varImp(lasso_fit_1))
```


## Model 2: Ridge logistic with full covariates

```{r}
f2 <- summerkill ~ variance_after_ice_30 + variance_after_ice_60 + log_schmidt +
  cumulative_above_10 + ice_duration + population + lon + lat + season + temp +
  max_bot + max_surf + mean_bot + mean_surf + max_bot_z + max_surf_z + mean_bot_z +
  mean_surf_z + layer_diff + quadratic_temp + peak_temp + cumulative_above_0 +
  cumulative_above_5
```

```{r}
par_grid <-  expand.grid(alpha = 0,
                        lambda = seq(1.8e-8, 3.5e-6, 
                                     length.out = 8))
cl <- makePSOCKcluster(8)
registerDoParallel(cl)

set.seed(825)
ridge_fit_2 <- train(f2, 
                     data = training, 
                     method = "glmnet", 
                     trControl = fitControl)
stopCluster(cl)
write_rds(ridge_fit_2, "../models/ridge_fit_2.rds")
```


## Model 3: Lasso logistic with month fixed effects

```{r}
m3_vars <- c(m1_vars, "month")

training <- historical_data %>%
  slice(in_training) %>%
  select(m3_vars)

testing  <- historical_data %>%
  slice(-in_training) %>%
  select(m3_vars)
```

```{r}
pre_proc_values <- preProcess(training, method = c("center", "scale"))
train_transformed <- predict(pre_proc_values, training)
test_transformed  <- predict(pre_proc_values, testing)
```

```{r}
cl <- makePSOCKcluster(6)
registerDoParallel(cl)

set.seed(825)
lasso_fit_3 <- train(summerkill ~ ., data = training, 
                 method = "glmnet", 
                 trControl = fitControl)

stopCluster(cl)
write_rds(lasso_fit_3, "../lasso_fit_3.rds")
```











```{r}
m1 <- cv.glmnet(summerkill ~ .,
                data = historical_data[in_training, c(m1_vars, "summerkill")],
                family = "binomial",
                parallel = TRUE, 
                type.measure = "auc",
                keep = TRUE
)

m2 <- cv.glmnet(summerkill ~ .,
                data = historical_data[in_training, c(m1_vars, "summerkill")],
                family = "binomial",
                parallel = TRUE, 
                type.measure = "auc",
                keep = TRUE
)
```

